DROP TABLE IF EXISTS certificate_tag;
DROP TABLE IF EXISTS purchase_certificate;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS certificate;
DROP TABLE IF EXISTS purchase;
DROP TABLE IF EXISTS user;

